"""neraca-lajur

Revision ID: 2f385a39f5d4
Revises: 9900857a6616
Create Date: 2024-11-07 08:14:40.890533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f385a39f5d4'
down_revision = '9900857a6616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('neraca_lajur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(length=5), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('daftar_akun_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daftar_akun_id'], ['daftar_akun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('neraca_lajur')
    # ### end Alembic commands ###
