"""jenis falsy

Revision ID: 3f253bf18434
Revises: fbe1082385e5
Create Date: 2024-11-09 02:06:19.079197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f253bf18434'
down_revision = 'fbe1082385e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neraca_lajur', schema=None) as batch_op:
        batch_op.alter_column('jenis',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neraca_lajur', schema=None) as batch_op:
        batch_op.alter_column('jenis',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###
