"""modal jurnal umum added

Revision ID: 9900857a6616
Revises: 3e8c07713388
Create Date: 2024-11-06 12:13:13.927747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9900857a6616'
down_revision = '3e8c07713388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurnal_umum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('daftar_akun_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daftar_akun_id'], ['daftar_akun.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jurnal_umum')
    # ### end Alembic commands ###
